application: clarity-db
module: default
version: unstable
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F4
automatic_scaling:
  max_idle_instances: 1

handlers:
- url: /favicon\.ico
  static_files: static/image/ClarityIcon_blue_16.png
  upload: static/image/ClarityIcon_blue_16.png

- url: /static
  static_dir: static

- url: /cron
  script: main.app
  login: admin

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest